# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28312c1f994c864be22430b63df320a3d3fddee833f2df151cfdd7b6bacfc1583d3d3991d3fb26a21cbb6a3da3b1d83c3d126073dd5d0433afd8759559027eb1

test:
  secret_key_base: a53a22de92fc264f8b4fee2da7a15eb71826be2fb7c7b9304bf1d31d3f0dbd6fa0cc3612653f47269e59811aa2840f706884a443e7b31f8fbaec11c2464d3cc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
